server:
  port: 18007

info:
  version: @project.version@

spring:
  application:
    name: @artifactId@
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: management.context-path=/foo, health.path=/ping, user.name=user, user.password=password
  profiles:
    active:
      - secure
  boot:
    admin:
      discovery:
        ignored-services: consul


management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
      base-path: /foo
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "user"
      password: "password"

